global class email_comp_cls {
    //public String approvalStatus{get; set;}
    //public employeeAttendance__c ea{get; set;}
    //public List<employeeAttendance__c> ls_emp{get; set;}

    public email_comp_cls(){
        //ea = new employeeAttendance__c();
        //approvalStatus = ea.approval_status__c;

        //ls_emp = [select ID, Employee_Name__c, Approval_Status__c, Description__c from employeeAttendance__c];
    }

    /*webservice static Id makeContact(String lastName, Account a) { 
        contact c = new contact(LastName = LastName, AccountID = a.Id); 
        return c.id; 
    }*/
}